config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  
  get 'profile', to:'pages#profile'
  
  get 'advisor', to: 'pages#advisor'
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        
    end
    
    def profile
    
    end
    
    def advisor
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/advisor.html.erb
<h1>This is the ADVISOR page</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'Profile', profile_path %>

app/views/pages/home.html.erb
<h1>This is the HOME page of my Finance Portfolio</h1>

<%= link_to "Profile", profile_path %>
<%= link_to "Advisor", advisor_path %>

app/views/pages/profile.html.erb
<h1> This is the PROFILE Page</h1>


<%= link_to "Home", root_path %>
<%= link_to "Advisor", advisor_path %>